#superuser permision when we used docker  
sudo: required
#travis-ci need docker CLI preinstalled and here travis-ci undrestand that he should copy the docker run 
services:
  - docker

#ce qu'il faut faire avant test,docn il faut builder notre img qui utilise Dockerfile.dev
before_install:
  #use tag with -t 
  - docker build -t khouloudsma/docker-react -f Dockerfile.dev .

script:
  - docker run khouloudsma/docker-react npm run test -- -- coverage

